[package]
name = "keenio_fetcher"
version = "0.1.0"
authors = ["Wu Young <doomsplayer@gmail.com>"]

[dependencies]
aster = "= 0.4.9"
quasi = "= 0.3.2"
hyper = "0.6.14"
chrono = "0.2.16"
serde_json = "0.6.0"
serde = "0.6.0"
serde_macros = "0.5.3"
redis = "*"
url = "0.2.37"
itertools = "0.4.0"
docopt = "*"
docopt_macros = "*"
rustc-serialize = "*"

[lib]
path = "src/lib.rs"
name = "keen"
crate-type = ["dylib", "rlib"]

[[bin]]
path = "src/main.rs"
name = "keen"

[profile.release]
debug = true

