[package]
name = "keenio_fetcher"
version = "0.1.0"
authors = ["Wu Young <doomsplayer@gmail.com>"]

[dependencies]
hyper = "0.6.14"
chrono = "0.2.16"
serde_json = "0.6.0"
serde = "0.6.0"
serde_macros = "0.5.3"
redis = "*"
itertools = "0.4.0"
docopt = "*"
docopt_macros = "*"
rustc-serialize = "*"
keen = "0.3.0"
regex = "0.1.41"
wrapped_enum = "0.1.3"
lazy_static = "0.1.15"
log = "0.3.2"
env_logger = "0.3.1"

[lib]
path = "src/lib.rs"
name = "keen_native"
crate-type = ["dylib", "rlib"]

[profile.release]
debug = true

